package com.cml.idex;

public enum ErrorCode {

   GENERIC,
   RESPONSE_PARSE_FAILED,
   UNKNOW_MARKET,
   UNKNOWN_ADDRESS,
   ORDER_FAILED,
   ORDER_NOT_FOUND,
   TRADE_FAILED,
   WITHDRAW_FAILED;
}
